### ISSUE TITLE
How to add icon to leading

### ISSUE THREAD

**Issue by dovandu** [joostlek/GradientAppBar#5]
when I change leading by code:
```dart
leading:new IconButton(
                icon: new Image.asset(XMIcons.iback, width: 25, height: 25,),
                tooltip: 'Back',
                onPressed: () => _onBack(),
              )
```

or
```dart
leading: new Center(
            child: new InkWell(
              onTap: onCancel,
              child: new Image.asset(XMIcons.iback, width: 25, height: 25,),
            ),
          )
```
then icon not show. Please help me!

**Comment by joostlek** [comment]
If it works with the normal AppBar, it should work with GradientAppBar, so if you find something that works on AppBar but doesn't work on GradientAppBar, then you got a bug for me :P

Regarding your problem, I'd suggest using an Icon instead of an Image.asset. I think that's the solution you're looking for
